//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsAppEntityFrameworkDbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Markalar
    {
        public int Id { get; set; }
        public string MarkaAdi { get; set; }
        public int StokMiktari { get; set; }
    }
}
